[package]
name = "vonage-to-matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
env_logger = "0.10"
hookshot = { path = "matrix-hookshot-rust" }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
vonage = { path = "vonage-rust" }
