[package]
name = "hookshot"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
reqwest_mock = "0.7"
